# -*- coding: utf-8 -*-
"""Data Extraction Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VWGY63mvkB71SXDjrBRa6vdvdYdfOsV
"""

from bs4 import BeautifulSoup
import requests

url = 'https://en.wikipedia.org/wiki/NIFTY_50'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

print(soup)

soup.find_all('table')[2]

soup.find('table',class_ = 'wikitable sortable')

table = soup.find_all('table')[2]

print(table)

nifty50 = table.find_all('th')

main_titles = nifty50[:4]
main_titles

main_table_titles = [title.text.strip() for title in main_titles]
main_table_titles

import pandas as pd

data_frame = pd.DataFrame(columns = main_table_titles)
data_frame

column_data = table.find_all('tr')
column_data

for row in column_data[1:]:
  data = row.find_all('th')
  row_data = row.find_all('td')
  individual_row_data = [data.text.strip() for data in data]
  individual_row_data += [data.text.strip() for data in row_data]
  print(individual_row_data)
  length = len(data_frame)
  data_frame.loc[length] = individual_row_data

data_frame

data_frame.to_csv('Companies.csv',index=False)

from google.colab import files

files.download('Companies.csv')